#!/bin/bash
credfile='/home/user/.gmail'

gmail_login=$(sed -n '1p' $credfile)
gmail_password=$(sed -n '2p' $credfile)

nbmail="$(wget --secure-protocol=TLSv1 --timeout=3 -t 1 -q -O - \
https://${gmail_login}:${gmail_password}@mail.google.com/mail/feed/atom \
--no-check-certificate | grep 'fullcount' \
| sed -e 's/.*<fullcount>//;s/<\/fullcount>.*//' 2>/dev/null)"

if [ -z "$nbmail" ]; then
echo "X"
else
  if [ $nbmail != 0 ]; then
    echo $nbmail
    # aplay ~/sounds/mail_here.wav
  else
  echo $nbmail
  fi
fi

